remote_theme: just-the-docs/just-the-docs
title: Learning Hub
description: Educational resources and tutorials
aux_links:
  "GitHub Repository":
    - "//github.com/yourusername/yourusername.github.io"

plugins:
  - jekyll-sass-converter

# Custom SCSS file
assets:
  stylesheets:
    - "/_sass/custom.scss"

